baseURL = 'https://lr2k.com/'
languageCode = 'en-us'
title = 'LR2K'

DefaultContentLanguage = "en"
[languages]
  [languages.en]
    languageName = "English"
    weight = 1
  [languages.fr]
    languageName = "Fran√ßais"
    weight = 2

## Site Settings
[params]
logo = "/img/Logo_Large_Transparent.png"
favicon = "/img/favicon.png"
copyright = 'LR2K'

# Credits
# This theme is forked from: https://github.com/startbootstrap/startbootstrap-grayscale
# This theme is forked by: https://github.com/akatiggerx04